version: 2.1
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
    - run:
        name: Install dependencies
        command: yarn
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: build code
          command: yarn build
      - persist_to_workspace:
          root: build
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/build
      - add_ssh_keys:
          fingerprints:
            - "00:59:75:e0:30:7c:67:60:46:7d:ce:78:c6:6b:62:9d"
      - run: ls build
      - run:
          name: Keyscan ssh host verification
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan 35.180.126.227 >> .ssh/known_hosts
      - run:
          name: Upload code to server
          command: scp -r build/* website@35.180.126.227:/home/website/zelda

workflows:
    build-and-deploy:
      jobs:
        - install-dependencies
        - build:
            requires:
              - install-dependencies
        - deploy:
            requires:
              - build